lots of changes

diff --git a/functions/error_encountered b/functions/error_encountered
--- a/functions/error_encountered
+++ b/functions/error_encountered
@@ -16,7 +16,7 @@ function error_encountered
         EXITCODE=1
     fi
 
-    echo "ERROR: previous command returned an error: status: $EXITCODE"
+    echo "ERROR: previous command returned an error: status: $EXITCODE" >&2
 
     if [ "${ERRMSG}" != "" ]
     then
