more changes

diff --git a/dbscripts/oracle/chk_nontemp_temp_tspace b/dbscripts/oracle/chk_nontemp_temp_tspace
--- a/dbscripts/oracle/chk_nontemp_temp_tspace
+++ b/dbscripts/oracle/chk_nontemp_temp_tspace
@@ -33,10 +33,11 @@ then
     exit 1
 fi
 
-if [ "$ORACLE_SID" = "" ] && [ "TWO_TASK" = "" ]
+if [ "${ORACLE_SID}" = "" ] && [ "${TWO_TASK}" = "" ]
 then
-    echo error: ORACLE_SID and TWO_TASK not set
-    exit 1
+    echo "ERROR: ORACLE_SID and TWO_TASK not set"
+    EXITCODE=1
+    exit ${EXITCODE}
 fi
 
 sqlplus -s ${SQLPLUS_DBA_LOGON} << *EOF* 2>&1 > /dev/null
@@ -58,7 +59,7 @@ status=$?
 
 if [ $status -ne 0 ]
 then
-    echo error: could not log on to check database
+    echo "ERROR: could not log on to check database"
     EXITCODE=1
 fi
 
diff --git a/dbscripts/oracle/chk_uname_pwd b/dbscripts/oracle/chk_uname_pwd
--- a/dbscripts/oracle/chk_uname_pwd
+++ b/dbscripts/oracle/chk_uname_pwd
@@ -36,10 +36,11 @@ else
     password=${2}
 fi
 
-if [ "$ORACLE_SID" = "" ] && [ "TWO_TASK" = "" ]
+if [ "${ORACLE_SID}" = "" ] && [ "${TWO_TASK}" = "" ]
 then
-    echo error: ORACLE_SID and TWO_TASK not set
-    exit 1
+    echo "ERROR: ORACLE_SID and TWO_TASK not set"
+    EXITCODE=1
+    exit ${EXITCODE}
 fi
 
 
@@ -52,12 +53,12 @@ status=$?
 
 if [ $status -ne 0 ]
 then
-    echo error: error running SQL\*Plus
+    echo "ERROR: error running SQL\*Plus"
     EXITCODE=1
 else
     if [ "$(echo $dummy | grep ORA-)" != "" ]
     then
-	echo error: could not connect
+	echo "ERROR: could not connect"
 	EXITCODE=1
     fi
 fi
diff --git a/dbscripts/oracle/convert_scn_number_to_logseq b/dbscripts/oracle/convert_scn_number_to_logseq
--- a/dbscripts/oracle/convert_scn_number_to_logseq
+++ b/dbscripts/oracle/convert_scn_number_to_logseq
@@ -38,16 +38,17 @@ then
 
     whichhost=$(echo ${2} | awk -F: '{print $2}' | tr "[:upper:]" "[:lower:]")
 
-    if [ "${whichhost}" = "" ] || [ "${whichhost}" = "${thishost}" ]
+    if [ "${whichhost}" = "" ] || [ "${whichhost}" = "${HOSTNAME}" ]
     then
-        whichhost=$thishost
+        whichhost=${HOSTNAME}
 
         if chkoradbinoratab ${ORACLE_SID}
         then
             :
         else
-            echo ERROR: $ORACLE_SID not in oratab
-            exit 1
+            echo "ERROR: ${ORACLE_SID} not in oratab"
+            EXITCODE=1
+            exit ${EXITCODE}
         fi
 
         . /usr/local/bin/oraenv 2>&1 > /dev/null
@@ -56,7 +57,7 @@ then
     shift
     shift
 else
-    whichhost=$thishost
+    whichhost=${HOSTNAME}
 fi
 
 if [ $# -ne 1 ]
@@ -65,20 +66,20 @@ then
 fi
 
 
-if [ "$ORACLE_SID" = "" ]
+if [ "${ORACLE_SID}" = "" ]
 then
-    echo ERROR: ORACLE_SID not set
+    echo "ERROR: ORACLE_SID not set"
     exit 1
 fi
 
 
-if [ "$whichhost" = "$thishost" ]
+if [ "$whichhost" = "${HOSTNAME}" ]
 then
-    if chkorainstsysdba $ORACLE_SID
+    if chkorainstsysdba ${ORACLE_SID}
     then
         :
     else
-        echo ERROR: $ORACLE_SID is not up
+        echo "ERROR: ${ORACLE_SID} is not up"
         exit 1
     fi
 
diff --git a/dbscripts/oracle/genccf b/dbscripts/oracle/genccf
--- a/dbscripts/oracle/genccf
+++ b/dbscripts/oracle/genccf
@@ -58,15 +58,15 @@ then
 
     whichhost=$(echo ${2} | awk -F: '{print $2}' | tr "[:upper:]" "[:lower:]")
 
-    if [ "${whichhost}" = "" ] || [ "${whichhost}" = "${thishost}" ]
+    if [ "${whichhost}" = "" ] || [ "${whichhost}" = "${HOSTNAME}" ]
     then
-        whichhost=$thishost
+        whichhost=${HOSTNAME}
 
         if chkoradbinoratab ${ORACLE_SID}
         then
             :
         else
-            echo ERROR: $ORACLE_SID not in oratab
+            echo "ERROR: ${ORACLE_SID} not in ${ORATAB}"
             exit 1
         fi
 
@@ -76,14 +76,15 @@ then
     shift
     shift
 else
-    whichhost=$thishost
+    whichhost=${HOSTNAME}
 fi
 
 
-if [ "$ORACLE_SID" = "" ]
+if [ "${ORACLE_SID}" = "" ]
 then
-    echo ERROR: ORACLE_SID not set
-    exit 1
+    echo "ERROR: ORACLE_SID not set"
+    EXITCODE=1
+    exit ${EXITCODE}
 fi
 
 
@@ -157,13 +158,13 @@ done
 TRACEFILE_IDENTIFIER=genccf$(date +%Y%m%d%H%M%S_${$})
 
 
-if [ "$whichhost" = "$thishost" ]
+if [ "$whichhost" = "${HOSTNAME}" ]
 then
-    if chkorainstsysdba $ORACLE_SID
+    if chkorainstsysdba ${ORACLE_SID}
     then
         :
     else
-        echo ERROR: $ORACLE_SID is not up
+        echo ERROR: ${ORACLE_SID} is not up
         exit 1
     fi
 
diff --git a/dbscripts/oracle/getpkgspec b/dbscripts/oracle/getpkgspec
--- a/dbscripts/oracle/getpkgspec
+++ b/dbscripts/oracle/getpkgspec
@@ -39,10 +39,11 @@ else
     package=${1}
 fi
 
-if [ "$ORACLE_SID" = "" ]
+if [ "${ORACLE_SID}" = "" ]
 then
-    echo ERROR: \$ORACLE_SID not set
-    exit 1
+    echo "ERROR: ORACLE_SID not set"
+    EXITCODE=1
+    exit ${EXITCODE}
 fi
 
 sqlplus -s ${SQLPLUS_DBA_LOGON} << *EOF* > $tmpfile
diff --git a/dbscripts/oracle/mkoraadmin b/dbscripts/oracle/mkoraadmin
--- a/dbscripts/oracle/mkoraadmin
+++ b/dbscripts/oracle/mkoraadmin
@@ -36,10 +36,11 @@ if [ $# -eq 1 ]
 then
     check_and_set_oracle_sid ${1}
 else
-    if [ "$ORACLE_SID" = "" ]
+    if [ "${ORACLE_SID}" = "" ]
     then
-	echo ERROR: ORACLE_SID not set
-	exit 1
+	echo "ERROR: ORACLE_SID not set"
+        EXITCODE=1
+	exit ${EXITCODE}
     fi
 
 fi
@@ -52,11 +53,11 @@ then
 fi
 
 
-ORAADMIN=$ORACLE_BASE/admin
-if [ ! -d $ORAADMIN ]
+ORAADMIN=${ORACLE_BASE}/admin
+if [ ! -d ${ORAADMIN} ]
 then
-    ORAADMIN=$ORACLE_HOME/admin
-    if [ ! -d $ORAADMIN ]
+    ORAADMIN=${ORACLE_HOME}/admin
+    if [ ! -d ${ORAADMIN} ]
     then
 	echo "WARNING: Could ont locate appropriate ORACLE_BASE/admin or ORACLE_HOME/admin directory"
 	echo "         Creating in CURRENT directory [${PWD}]"
@@ -71,7 +72,7 @@ then
 
     if [ $? -ne 0 ]
     then
-        echo ERROR: Could not create toplevel ${ORACLE_SID} directory in $ORAADMIN
+        echo "ERROR: Could not create toplevel ${ORACLE_SID} directory in ${ORAADMIN}"
         exit 1
     fi
 
