more changes

diff --git a/dbscripts/oracle/dbcntl b/dbscripts/oracle/dbcntl
--- a/dbscripts/oracle/dbcntl
+++ b/dbscripts/oracle/dbcntl
@@ -23,7 +23,6 @@ CS_TOP=${CS_TOP:-/opt/dsp}
 . ${CS_TOP}/env/dsp.env
 . ${CS_TOP}/env/funcs.sh
 
-
 USAGE_STRING="SID [mode]"
 
 umask 022
@@ -37,8 +36,16 @@ else
     mode=$(echo $2 | tr [:upper:] [:lower:])
 fi
 
-. /usr/local/bin/oraenv 2>&1 > /dev/null
+if chkoradbinoratab ${ORACLE_SID}
+then
+    :
+else
+    echo "ERROR: $ORACLE_SID not in [${ORATAB}]"
+    EXITCODE=1
+    exit ${EXITCODE}
+fi
 
+. /usr/local/bin/oraenv 2>&1 > /dev/null
 
 
 #
@@ -93,7 +100,7 @@ exit
 
     sleep 2
 
-    if isinstup ${ORACLE_SID}
+    if isinstup ${ORACLE_SID} 2>&1 > /dev/null
     then
 	scriptout "WARNING: $ORACLE_SID appears to still to be up"
 	EXITCODE=2
@@ -102,7 +109,7 @@ exit
 
 function startup_db
     {
-    if isinstup ${ORACLE_SID}
+    if isinstup ${ORACLE_SID} 2>&1 > /dev/null
     then
 	scriptout "WARNING: $ORACLE_SID appears to already be up"
 	EXITCODE=2
@@ -132,7 +139,7 @@ startup $startup_mode
 exit
 *EOF*
 
-    if isinstup ${ORACLE_SID}
+    if isinstup ${ORACLE_SID} 2>&1 > /dev/null
     then
 	: # do nothing
     else
diff --git a/dbscripts/oracle/getinfo-oradb b/dbscripts/oracle/getinfo-oradb
--- a/dbscripts/oracle/getinfo-oradb
+++ b/dbscripts/oracle/getinfo-oradb
@@ -1,4 +1,5 @@
 #!/bin/bash
+set +x
 
 #+++___________________________________________________________________________________
 #
@@ -55,9 +56,9 @@ if [ "${ORACLE_SID}" = "" ]
 then
     echo "ERROR: ORACLE_SID not set and not passed via command line - exiting"
     exit 1
-else
-    . ${ORAENV} 2>&1 > /dev/null
-    status=$?
+#else
+#    . ${ORAENV} 2>&1 > /dev/null
+#    status=$?
 fi
 
 
@@ -148,6 +149,24 @@ print_begin ${TAG}
 padding="    ${padding}"
 echo "${padding}ORACLE_SID:        ${ORACLE_SID}"
 echo ""
+
+if chkoradbinoratab ${ORACLE_SID}
+then
+    :
+else
+    echo "ERROR: $ORACLE_SID not in [${ORATAB}]"
+    EXITCODE=1
+    exit ${EXITCODE}
+fi
+
+if chkorainstsysdba $ORACLE_SID
+then
+    :
+else
+    echo "ERROR: $ORACLE_SID is not up"
+    EXITCODE=1
+    exit ${EXITCODE}
+fi
 
 #
 # Determine version
diff --git a/scripts/rm_after_time b/scripts/rm_after_time
--- a/scripts/rm_after_time
+++ b/scripts/rm_after_time
@@ -45,6 +45,12 @@ fi
 seconds=$1
 file=$2
 
+if [ ! -f ${file} ]
+then
+    echo "ERROR: file [${file}] does not exist - exiting"
+    exit 1
+fi
+
 sleep $seconds
 
 [ -f $file ] && rm -f $file
