more changes

diff --git a/dbscripts/oracle/getinfo-orahome b/dbscripts/oracle/getinfo-orahome
--- a/dbscripts/oracle/getinfo-orahome
+++ b/dbscripts/oracle/getinfo-orahome
@@ -3,7 +3,7 @@
 #+++___________________________________________________________________________________
 #
 #
-# Script name:                  getinfo-ohome
+# Script name:                  getinfo-orahome
 #
 # Description:
 #
@@ -23,15 +23,17 @@ CS_TOP=/opt/dsp
 . ${CS_TOP}/env/dsp.env
 . ${CS_TOP}/env/funcs.sh
 
-USAGE_STRING="[-o ORACLE_HOME] [-m lite|basic|comp]"
+USAGE_STRING="[-o ORACLE_HOME] [-m lite|basic|comp] [-s human|machine]"
 
 mode="lite"
+style="human"
 
-while getopts 'o:m:' OPTION
+while getopts 'o:m:s:' OPTION
 do
     case "$OPTION" in
         o) ORACLE_HOME=$OPTARG ;;
         m) mode=$OPTARG ;;
+        s) style=$OPTARG ;;
         ?) usage ;;
     esac
 done
@@ -40,8 +42,20 @@ case "${mode}" in
     [lL][iI][tT][eE] ) mode=lite ;;
     [bB][aA][sS][iI][cC] ) mode=basic ;;
     [cC][oO][mM][pP] ) mode=comp ;;
-    *) echo ERROR ;;
+    *) echo "ERROR: invalid mode [${mode}] - exiting" ; exit 1 ;;
 esac
+
+case "${style}" in
+    [hH][uU][mM][aA][nN]) style=human;;
+    [mM][aA][cC][hH][iI][nN][eE]) style=machine;;
+    *) echo "ERROR: invalid style [${style}] - exiting" ; exit 1 ;;
+esac
+
+if [ "${ORACLE_HOME}" = "" ]
+then
+    echo "ERROR: ORACLE_HOME not set and not passed via command line - exiting"
+    exit 1
+fi
 
 
 if [ ! -d ${ORACLE_HOME} ]
@@ -66,7 +80,13 @@ function print_begin
         let lvl=${lvl}+1
     done
 
-    echo "${padding}<BEGIN_${1}>"
+    if [ "${style}" = "human" ]
+    then
+        echo "${padding}${1}"
+        echo "${padding}---------------------------------------------------"
+    else
+        echo "${padding}<BEGIN_${1}>"
+    fi
     }
 
 
@@ -80,7 +100,12 @@ function print_end
         let lvl=${lvl}+1
     done
 
-    echo "${padding}<END_${1}>"
+    if [ "${style}" = "human" ]
+    then
+        echo ""
+    else
+        echo "${padding}<END_${1}>"
+    fi
     }
 
 
@@ -89,10 +114,26 @@ function show_databases
     level=$1
     TAG=DATABASES
 
-    echo "ORACLE_HOME:   ${ORACLE_HOME}"
-    echo ""
     print_begin ${TAG}
-    awk -F: -v v_ohome=${ORACLE_HOME} '$2==v_ohome {print $1}' ${ORATAB} | grep ^[a-zA-Z0-9_$] | sort | sed -e 's/^/        /'
+
+    padding="    ${padding}"
+
+    for DB in $(awk -F: -v v_ohome=${ORACLE_HOME} '$2==v_ohome {print $1}' ${ORATAB} | grep ^[a-zA-Z0-9_$] | sort)
+    do
+        echo -n "${padding}${DB}:"
+
+        if isinstup ${DB} 2>&1 > /dev/null
+        then
+            instance_status=$(${scriptdir}/sqlx -d ${DB} select \'STATUS=\' \|\| status from v\$instance 2>/dev/null | grep ^STATUS= | cut -d= -f2)
+
+            [ "${instance_status}" = "STARTED" ] && instance_status="NOMOUNT"
+        else
+            instance_status="DOWN"
+        fi
+
+        echo "instance:${instance_status}"
+    done
+
     print_end ${TAG}
     }
 
@@ -102,10 +143,14 @@ function show_opatch_version
     TAG=OPATCH_VERSION
 
     print_begin ${TAG}
-    ${ORACLE_HOME}/OPatch/opatch version | sed -e s'/^/        /'
+
+    padding="    ${padding}"
+    ${ORACLE_HOME}/OPatch/opatch version | sed -e s"/^/${padding}/"
     status=$?
+
     print_end ${TAG}
     }
+
 
 function show_opatch_lspatches
     {
@@ -113,10 +158,14 @@ function show_opatch_lspatches
     TAG=OPATCH_LSPATCHES
 
     print_begin ${TAG}
-    ${ORACLE_HOME}/OPatch/opatch lspatches | sed -e s'/^/        /'
+
+    padding="    ${padding}"
+    ${ORACLE_HOME}/OPatch/opatch lspatches | sed -e s"/^/${padding}/"
     status=$?
+
     print_end ${TAG}
     }
+
 
 function show_opatch_lsinventory
     {
@@ -124,12 +173,13 @@ function show_opatch_lsinventory
     TAG=OPATCH_LSINVENTORY
 
     print_begin ${TAG}
-    ${ORACLE_HOME}/OPatch/opatch lsinventory | sed -e s'/^/        /'
+
+    padding="    ${padding}"
+    ${ORACLE_HOME}/OPatch/opatch lsinventory | sed -e s"/^/${padding}/"
     status=$?
+
     print_end ${TAG}
     }
-
-LEVEL=1
 
 
 #
@@ -143,9 +193,13 @@ LEVEL=1
 set_error_trap
 
 level=1
-TAG=ORACLE_HOME_DATABASE
+TAG=ORACLE_HOME-DATABASE
 
 print_begin ${TAG}
+
+padding="    ${padding}"
+echo "${padding}LOC: ${ORACLE_HOME}"
+echo 
 
 (
 #
@@ -156,7 +210,7 @@ show_databases 2
 show_opatch_version 2
 show_opatch_lspatches 2
 
-if [ "${mode}" = "comp} " ]
+if [ "${mode}" = "comp" ]
 then
     show_opatch_lsinventory 2
 fi
