More changes

diff --git a/scripts/bkup b/scripts/bkup
--- a/scripts/bkup
+++ b/scripts/bkup
@@ -30,55 +30,47 @@ then
     usage
 fi
 
+now=$(date +%Y%m%d)
+
+if [ "${now}" = "" ]
+then
+    echo "ERROR: date command does not seem to work - manual/alternate backup required - exiting"
+    EXITCODE=1
+    exit ${EXITCODE}
+fi
+
 for filename in ${*}
 do
     if [ -f $filename -o -d $filename ]
     then
-	if [ -f $filename.$today -o -d $filename.$today ]
+        bkupfilename=${filename}.$(date +%Y%m%d)
+        [ -f ${bkupfilename} ] && bkupfilename=${filename}.$(date +%Y%m%d_%H%M)
+        [ -f ${bkupfilename} ] && bkupfilename=${filename}.$(date +%Y%m%d_%H%M%S)
+        [ -f ${bkupfilename} ] && bkupfilename=${filename}.$(date +%Y%m%d_%H%M%S).${$}
+
+        while [ -f ${bkupfilename} ]
+        do
+            bkupfilename=${bkupfilename}.${$}
+        done        
+
+        cp -rp ${filename} ${bkupfilename}
+	status=$?
+
+	if [ $status -ne 0 ]
 	then
-	    echo error: backup file/directory for $filename already exists
-	    EXITCODE=1
-	else
-	    if [ -f $filename ]
-	    then
-		cp -p $filename $filename.$today
-		status=$?
-
-		if [ $status -ne 0 ]
-		then
-		    echo error: could not copy $filename to $filename.$today
-		    EXITCODE=1
-		fi
-
-                ls -ald $filename
-                ls -ald $filename.$today
-	    elif [ -d $filename ]
-	    then
-		cp -rp $filename $filename.$today
-		status=$?
-
-		if [ $status -ne 0 ]
-		then
-		    echo error: could not copy $filename to $filename.$today
-		    EXITCODE=1
-		fi
-
-                ls -ald $filename
-                ls -ald $filename.$today
-	    else
-		echo error: $filename not a regular file or directory
-	    fi
+		echo error: could not copy $filename to $filename.$today
+		EXITCODE=1
 	fi
+
+        echo
+        ls -ald $filename
+        ls -ald ${bkupfilename}
+        echo
     else
-	echo error: $filename not a regular file or directory
-	EXITCODE=1
+	echo "ERROR: $filename not a regular file or directory - exiting"
+	EXITCODE=2
+        exit ${EXITCODE}
     fi
 done
-
-if [ $EXITCODE -ne 0 ]
-then
-    echo
-    echo ERROR: See above for information
-fi
 
 exit $EXITCODE
