more changes

diff --git a/scripts/serverstamp b/scripts/serverstamp
--- a/scripts/serverstamp
+++ b/scripts/serverstamp
@@ -58,6 +58,7 @@ then
 fi
 
 owner=$(cut -d: -f1 ${DSP_OWNER_FILE})
+dspserverid=$(grep ^dspserverid: ${DSP_IDENTITY_FILE} | cut -d: -f2)
 
 if [ "${user}" != "${owner}" ]
 then
@@ -86,7 +87,7 @@ echo
 if [ "${newid}" != "" ] && [ $status -eq 0 ]	# uuidgen exists and we could generate our own uuid
 then
   unset selections
-  selections=("Generate a server ID" "Provide a UUID to use for server ID")
+  selections=("Generate a server ID" "Provide a UUID to use for server ID" "Keep existing")
   choose_from_menu "Please select a MAC address to use to stamp this server" selected_choice "${selections[@]}"
   echo "Selected choice: $selected_choice"
 
@@ -94,6 +95,15 @@ then
   then
       echo -n "Enter the UUID you wish to stamp for this server: "
       read newid
+  elif [ "${selected_choice}" = "Keep existing" ]
+  then
+      if [ "${dspserverid}" = "" ]
+      then
+          echo "ERROR: Keep existing requires dspserverid to be set in ${DSP_IDENTITY_FILE} but it is not found - exiting"
+          EXITCODE=1
+          exit $EXITCODE
+      fi
+      newid=$(echo ${dspserverid})	# echo to help get rid of whitespace
   fi
 fi
 
